In [6]:
import tensorflow as tf
print(tf.__version__)


2.13.0


In [8]:
# !pip install tensorflow
!pip install --upgrade tensorflow


Unable to create process using 'C:\Users\KOTNI KANAKA RAJU\anaconda3\python.exe "C:\Users\KOTNI KANAKA RAJU\anaconda3\Scripts\pip-script.py" install --upgrade tensorflow'


In [9]:
from tensorflow.keras.preprocessing.text import one_hot


In [12]:
mark=['Sometimes to understand a word',
      'meaning you need more than a definition;',
      'you need to see the word used in a sentence.',
      'At YourDictionary,',
      'we give you the tools to learn what a word means',
      'and how to use it correctly.',
      ' With this sentence maker,'
      'simply type a word in the search bar and see a variety of sentences',
      'with that word used in its different ways.',
      'Our sentence generator can provide more context and relevance,',
      'ensuring you use a word the right',]

In [13]:
# size of mark
mark
voc_size=9000

# one hot representation

In [15]:
onehot_rep=[one_hot(words,voc_size) for words in mark]
print(onehot_rep)

[[5451, 8361, 1999, 7473, 6250], [8196, 8301, 5557, 3351, 4229, 7473, 5328], [8301, 5557, 8361, 8286, 5947, 6250, 5785, 5861, 7473, 2415], [5914, 772], [4659, 5138, 8301, 5947, 8242, 8361, 8957, 6374, 7473, 6250, 2181], [8985, 8475, 8361, 1677, 1368, 4426], [4259, 8857, 2415, 7658, 1779, 5103, 7473, 6250, 5861, 5947, 440, 982, 8985, 8286, 7473, 7538, 6351, 3156], [4259, 655, 6250, 5785, 5861, 3736, 6709, 8803], [7015, 2415, 845, 8822, 8169, 3351, 1852, 8985, 5551], [849, 8301, 1677, 7473, 6250, 5947, 1263]]


# word embedding representation

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
import numpy as np
mark_length=10
docs=pad_sequences(onehot_rep,padding='pre',maxlen=mark_length)
print(docs)


[[   0    0    0    0    0 5451 8361 1999 7473 6250]
 [   0    0    0 8196 8301 5557 3351 4229 7473 5328]
 [8301 5557 8361 8286 5947 6250 5785 5861 7473 2415]
 [   0    0    0    0    0    0    0    0 5914  772]
 [5138 8301 5947 8242 8361 8957 6374 7473 6250 2181]
 [   0    0    0    0 8985 8475 8361 1677 1368 4426]
 [5861 5947  440  982 8985 8286 7473 7538 6351 3156]
 [   0    0 4259  655 6250 5785 5861 3736 6709 8803]
 [   0 7015 2415  845 8822 8169 3351 1852 8985 5551]
 [   0    0    0  849 8301 1677 7473 6250 5947 1263]]


In [18]:
dim=12
model=Sequential()
model.add(Embedding(voc_size,12,input_length=mark_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 12)            108000    
                                                                 
Total params: 108000 (421.88 KB)
Trainable params: 108000 (421.88 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
print(model.predict(docs))

1/1 [==============================] - 0s 269ms/step
[[[-0.04958808  0.03374591  0.0139791  ... -0.01639698  0.0222565
    0.02595313]
  [-0.04958808  0.03374591  0.0139791  ... -0.01639698  0.0222565
    0.02595313]
  [-0.04958808  0.03374591  0.0139791  ... -0.01639698  0.0222565
    0.02595313]
  ...
  [-0.00424879 -0.00995036 -0.00432427 ... -0.04441849  0.01586796
   -0.04245093]
  [ 0.02983317 -0.04009646 -0.01720155 ... -0.02707152 -0.04055163
   -0.00791986]
  [-0.01124772 -0.01767185 -0.04860995 ... -0.03410701  0.02171007
    0.03281882]]

 [[-0.04958808  0.03374591  0.0139791  ... -0.01639698  0.0222565
    0.02595313]
  [-0.04958808  0.03374591  0.0139791  ... -0.01639698  0.0222565
    0.02595313]
  [-0.04958808  0.03374591  0.0139791  ... -0.01639698  0.0222565
    0.02595313]
  ...
  [ 0.00181741  0.03476613 -0.0197521  ...  0.04139248  0.02630312
   -0.00953291]
  [ 0.02983317 -0.04009646 -0.01720155 ... -0.02707152 -0.04055163
   -0.00791986]
  [-0.02379284 -0.0312747 

In [21]:
docs[0]

array([   0,    0,    0,    0,    0, 5451, 8361, 1999, 7473, 6250])

In [22]:
print(model.predict(docs[0]))

1/1 [==============================] - 0s 47ms/step
[[-0.04958808  0.03374591  0.0139791   0.04324634  0.0321314  -0.0044161
  -0.03444542  0.0111552  -0.02307671 -0.01639698  0.0222565   0.02595313]
 [-0.04958808  0.03374591  0.0139791   0.04324634  0.0321314  -0.0044161
  -0.03444542  0.0111552  -0.02307671 -0.01639698  0.0222565   0.02595313]
 [-0.04958808  0.03374591  0.0139791   0.04324634  0.0321314  -0.0044161
  -0.03444542  0.0111552  -0.02307671 -0.01639698  0.0222565   0.02595313]
 [-0.04958808  0.03374591  0.0139791   0.04324634  0.0321314  -0.0044161
  -0.03444542  0.0111552  -0.02307671 -0.01639698  0.0222565   0.02595313]
 [-0.04958808  0.03374591  0.0139791   0.04324634  0.0321314  -0.0044161
  -0.03444542  0.0111552  -0.02307671 -0.01639698  0.0222565   0.02595313]
 [-0.00097606  0.04189286 -0.04202757 -0.03012083  0.0321109  -0.03651981
  -0.03304144  0.01886055 -0.02908676 -0.03924248  0.02283495  0.00975889]
 [ 0.03862995 -0.03870855  0.03644668 -0.02298547 -0.001207